---
title: "Projeto Inadimplencia"
output: html_document
date: "2022-12-11"
---
install.packages("readr")
install.packages("ggplot2")
install.packages("devtools")
install.packages("gmodels")
install.packages("tidyr")
install.packages("rpart")
install.packages("rpart.plot")
install.packages("dplyr")
install.packages("randomForest")
install.packages("caret")
install.packages("Hmisc")
install.packages("remotes")
remotes::install_cran("azuremlsdk")
remotes::install_github('https://github.com/Azure/azureml-sdk-for-r')
azuremlsdk::install_azureml(remove_existing_env = TRUE)
reticulate::py_install("azureml-dataprep==1.4.2", envname = "r-reticulate", pip = TRUE)


library("Hmisc")
library("tidyr")
library(rpart)
library(rpart.plot)
library(dplyr)
library(randomForest)
library("ggplot2")
library(caret)
library("readr")
library("azuremlsdk")


getwd()

data <- read.csv("loan_default_data_loan_default.csv")


data[data == NA] <- 0
head(data)
str(data)
dataRemove <-subset(data, select = -c(ID, year, rate_of_interest, Interest_rate_spread,	Upfront_charges, dtir1))
print(dataRemove)
dataClean <- na.omit(dataRemove)


print(dataClean)
summary(dataClean)
head(dataClean)

name <- "grupo-demo-01iar01"

ws <- get_workspace(name, subscription_id = "c40d32a1-644a-434d-8a67-8e2b12e4d891", resource_group = "Turma01IAR")

experiment(ws, "inadimplencia_r")

saidaStatus <- glm(formula = Status ~ loan_amount + Gender, data = dataClean, family = binomial)

newdata <- data.frame(loan_amount = 676500, Gender = 'Male')
predict(saidaStatus, newdata, type = "response")

saveRDS(saidaStatus, "saidaStatus.rds")
